import os
from app.config import settings
from app.models.schemas import AnalysisResult

async def generate_report(analysis: AnalysisResult) -> str:
    os.makedirs(settings.REPORTS_DIR, exist_ok=True)
    report_path = os.path.join(settings.REPORTS_DIR, f"{analysis.id}.html")
    
    explanation_html = ""
    if analysis.explanation:
        findings_html = "".join([f"<li>{f}</li>" for f in analysis.explanation.keyFindings])
        explanation_html = f"""
        <div class="section">
            <h2>AI Explanation</h2>
            <p><strong>Summary:</strong> {analysis.explanation.summary}</p>
            <p><strong>Risk Level:</strong> {analysis.explanation.riskLevel}</p>
            <p><strong>Explanation:</strong> {analysis.explanation.explanation}</p>
            <p><strong>Recommendation:</strong> {analysis.explanation.recommendation}</p>
            <h3>Key Findings:</h3>
            <ul>{findings_html}</ul>
        </div>
        """
        
    indicators_html = "".join([
        f"<li><strong>{ind.name}:</strong> {ind.score}/100 - {ind.description or ''}</li>" 
        for ind in analysis.indicators
    ])

    html_content = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <title>CraftVerse AI Detector Report - {analysis.originalFilename}</title>
        <style>
            body {{ font-family: Arial, sans-serif; line-height: 1.6; max-width: 800px; margin: 0 auto; padding: 20px; }}
            h1 {{ color: #2c3e50; border-bottom: 2px solid #3498db; padding-bottom: 10px; }}
            .section {{ background: #f9f9f9; padding: 15px; margin-bottom: 20px; border-radius: 5px; }}
            .verdict {{ font-size: 1.2em; font-weight: bold; color: #e74c3c; }}
            .authentic {{ color: #27ae60; }}
            .footer {{ margin-top: 40px; font-size: 0.8em; color: #7f8c8d; text-align: center; border-top: 1px solid #eee; padding-top: 10px; }}
        </style>
    </head>
    <body>
        <h1>CraftVerse AI Detection Report</h1>
        
        <div class="section">
            <h2>Overview</h2>
            <p><strong>File Name:</strong> {analysis.originalFilename}</p>
            <p><strong>Analysis ID:</strong> {analysis.id}</p>
            <p><strong>Date:</strong> {analysis.createdAt}</p>
            <p><strong>Media Type:</strong> {analysis.mediaType}</p>
            
            <p><strong>Verdict:</strong> <span class="verdict {'authentic' if analysis.verdict == 'LIKELY_AUTHENTIC' else ''}">{analysis.verdict}</span></p>
            <p><strong>Confidence:</strong> {analysis.confidence.upper()}</p>
        </div>
        
        <div class="section">
            <h2>Scores</h2>
            <p><strong>AI Probability:</strong> {analysis.aiProbability}%</p>
            <p><strong>Authentic Probability:</strong> {analysis.realProbability}%</p>
            <p><strong>Manipulation Probability:</strong> {analysis.manipulationProbability}%</p>
        </div>
        
        {explanation_html}
        
        <div class="section">
            <h2>Detection Indicators</h2>
            <ul>
                {indicators_html or "<li>No specific indicators available</li>"}
            </ul>
        </div>
        
        <div class="footer">
            <p>Generated by CraftVerse AI Detector. This report provides an algorithmic assessment and should be used as one of several factors in determining media authenticity.</p>
        </div>
    </body>
    </html>
    """
    
    with open(report_path, 'w', encoding='utf-8') as f:
        f.write(html_content)
        
    return report_path
